
# Include project configurations.
include $(LEVEL)/Makefile.config

# Include LLVM's master Makefile.
include $(LLVM_SRC_ROOT)/Makefile.common

LLVMBuildTool := $(LLVM_SRC_ROOT)/utils/llvm-build/llvm-build

# Include custom rules
include $(PROJ_SRC_ROOT)/Makefile.rules
